export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (<>
          {children}
          <footer style={{backgroundColor:'whitesmoke'}}>Footer</footer>
    </>
    )
  }
  