import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute:'',
    default:'next.js -tutorial',
    template:'%S | Codevolution',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'blueviolet', padding:'2rem'}}>Header</header>
        {children}
        <footer style={{backgroundColor:'whitesmoke'}}>Footer</footer>
        </body>
    </html>
  )
}
