export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'blueviolet', padding:'2rem'}}>Header</header>
        {children}
        <footer style={{backgroundColor:'whitesmoke'}}>Footer</footer>
        </body>
    </html>
  )
}
