"client side"
import { Metadata } from "next"
import { usePathname } from "next/navigation"

export const metadata: Metadata = {
  title: {
    absolute:'',
    default:'next.js -tutorial',
    template:'%S | Codevolution',
  },
  description: 'Generated by Next.js',
}
const navLinks=[
    {"title":'Register', "href":"/register"},{"title":'login', "href":"/login"},{"title":'forgotPassword', "href":"/forgotPassword"}
  ]
export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const pathname = usePathname();

  return (<>
  {
    navLinks.map((links)=>{<div> {links.title}</div>})
  }
  </>
  )
}
