"use client"
import { Metadata } from "next"
import { usePathname } from "next/navigation"
import Link from "next/link"
import { useState } from "react"

const metadata: Metadata = {
  title: {
    absolute:'',
    default:'next.js -tutorial',
    template:'%S | Codevolution',
  },
  description: 'Generated by Next.js',
}
const navLinks=[
    {"title":'Register', "href":"/register"},{"title":'login', "href":"/login"},{"title":'forgotPassword', "href":"/forgotPassword"}
  ]
export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const pathname = usePathname();
    const [input, setInput] =useState('');

  return (<div>
  <div>
    <input value={input} onChange={(e)=>setInput(e.target.value)}/>
  </div>
   {
        navLinks.map((link)=>{
          const isActive = pathname.startsWith(link.href)
          return <Link href={`${link.href}`} key={link.title} className={isActive ? "font-bold mr-4":"text-blue-500 mr-4"}>{link.title}</Link>
        })
      }
      {children}
  </div>
  )
}
